"""Drive state-actor to produce a bloated geth datadir that prefunds our seed.

state-actor (https://github.com/nerolation/state-actor) writes a client-native
datadir with synthetic/bloated state and the genesis baked in — no `geth init`.
Production genesis alloc is always empty, so to have our funding seed present
on the bloated chain we declare it in a one-entity `--spec` YAML.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

# 1,000,000 ETH — generous so the seed can fund any test on the bloated chain.
DEFAULT_SEED_BALANCE_WEI = 10**24


def write_seed_spec(seed_addr: str, path: Path, balance_wei: int = DEFAULT_SEED_BALANCE_WEI) -> Path:
    """Write a minimal state-actor spec prefunding ``seed_addr``."""
    addr = seed_addr if seed_addr.startswith("0x") else f"0x{seed_addr}"
    path.write_text(
        "# Auto-generated by eest-replay: prefund the EEST submit seed account\n"
        "# on the state-actor bloated chain.\n"
        "entities:\n"
        "  - kind: eoa\n"
        f"    address: {addr}\n"
        f'    balance: "{balance_wei}"\n'
    )
    return path


def run_state_actor(
    binary: Path,
    db_dir: Path,
    *,
    seed_addr: str,
    chain_id: int,
    fork: str,
    target_size: str | None = None,
    seed_balance_wei: int = DEFAULT_SEED_BALANCE_WEI,
) -> Path:
    """
    Run state-actor to produce a bloated geth datadir prefunding ``seed_addr``.

    Returns the datadir to boot geth against (the parent of ``geth/chaindata``).
    ``fork`` is lowercase as state-actor expects (e.g. "osaka", "prague").
    ``target_size`` (e.g. "200MB", "5GB") adds mainnet-shaped bloat on top of
    the seed entity; omit it to write only the seed (no bloat).
    """
    db_dir = db_dir.resolve()
    db_dir.mkdir(parents=True, exist_ok=True)
    spec_path = write_seed_spec(seed_addr, db_dir / "seed-spec.yaml", seed_balance_wei)
    # geth requires the chaindata path to end in /geth/chaindata.
    chaindata = db_dir / "geth" / "chaindata"

    cmd = [
        str(binary),
        "--client", "geth",
        "--db", str(chaindata),
        "--spec", str(spec_path),
        "--chain-id", str(chain_id),
        "--fork", fork.lower(),
    ]
    if target_size:
        cmd += ["--target-size", target_size]

    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)
    if proc.returncode != 0:
        tail = "\n".join((proc.stdout + proc.stderr).splitlines()[-15:])
        raise RuntimeError(f"state-actor exited {proc.returncode}:\n{tail}")
    return db_dir
